name: playatlas-dev

services:
  app-dev:
    build:
      context: ..
      dockerfile: ./Dockerfile
      target: dev
    container_name: app-dev
    environment:
      LOG_LEVEL: 0
    volumes:
      - playnite-insights-dev-data:/app/data
      - ..:/workspace:cached

volumes:
  playnite-insights-dev-data:
