name: playnite-insights-dev

services:
  app-dev:
    build:
      context: ..
      dockerfile: ./Dockerfile
      target: dev
    environment:
      TZ: America/Sao_Paulo
      ORIGIN: ${ORIGIN_DEV} # make sure there's no trailing slash
      LOG_LEVEL: 0
      PLAYNITE_HOST_ADDRESS: ${PLAYNITE_HOST_ADDRESS}
    volumes:
      - playnite-insights-dev-data:/app/data
      - ..:/workspace:cached
    networks:
      - services-ipv6

volumes:
  playnite-insights-dev-data:

networks:
  services-ipv6:
    external: true
